name: tun_rokh_demo
description: Tun Rokh Application.

publish_to: 'none'

version: 1.0.1-rc

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.1.0
  provider: ^6.0.1
  expansion_tile_card: ^2.0.0
  carousel_slider: ^4.0.0
  shared_preferences: ^2.0.8
  flutter_spinkit: ^5.1.0
  auto_size_text: ^3.0.0
  flutter_staggered_animations: ^1.0.0
  connectivity: ^3.0.6
  url_launcher: ^6.0.13
  geolocator: ^7.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/answer_images/
  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Regular.ttf
          weight: 500
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 400
    - family: Prompt
      fonts:
      - asset: assets/fonts/Prompt-Bold.ttf
        weight: 700
      - asset: assets/fonts/Prompt-Regular.ttf
        weight: 500
      - asset: assets/fonts/Prompt-Light.ttf
        weight: 400
